# Generated by Django 4.1.3 on 2022-11-23 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('companyname', models.CharField(blank=True, max_length=150, null=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='companylogo/')),
                ('problem', models.TextField(blank=True, max_length=500, null=True)),
                ('is_approved', models.BooleanField(blank=True, default=False, null=True)),
                ('status', models.CharField(blank=True, default='Pending', max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
