# Generated by Django 4.1.3 on 2022-11-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('companyname', models.CharField(max_length=150)),
                ('company_logo', models.ImageField(upload_to='companylogo/')),
                ('team_background_details', models.TextField()),
                ('company_and_product_details', models.TextField()),
                ('problem', models.TextField()),
            ],
        ),
    ]
