# Generated by Django 4.1.3 on 2022-11-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_application_created_date_application_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='New', max_length=100),
        ),
    ]
