# Generated by Django 4.1.3 on 2022-11-23 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='applicant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.application'),
        ),
    ]
