# Generated by Django 4.1.3 on 2022-11-20 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_application_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='team_background_details',
            new_name='team_background',
        ),
    ]
