# Generated by Django 4.1.3 on 2022-11-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_team_background_details_application_team_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='company_and_product_details',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='application',
            name='problem',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='application',
            name='team_background',
            field=models.TextField(max_length=500),
        ),
    ]
