# Generated by Django 4.1.3 on 2022-11-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_application_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
