# Generated by Django 4.1.3 on 2022-11-20 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
