# Generated by Django 4.1.3 on 2022-11-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='company_and_product_details',
        ),
        migrations.RemoveField(
            model_name='application',
            name='team_background',
        ),
        migrations.AlterField(
            model_name='application',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='companylogo/'),
        ),
    ]
