# Generated by Django 4.1.3 on 2022-11-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_application_company_and_product_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
